name: OHM Upstream Sync

on:
  schedule:
    - cron: "20 5,17 * * *"
  workflow_dispatch:

jobs:
  upstream-sync:
    name: Upstream Sync
    permissions:
      contents: write
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Check out our repository
        uses: actions/checkout@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          fetch-depth: 0

      - name: Check out upstream master
        env:
          UPSTREAM: https://github.com/tyrasd/overpass-turbo
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@users.noreply.github.com"
          git remote add upstream "${UPSTREAM}"
          git fetch upstream master

      - name: List all branches
        run: |
          git branch --all | egrep 'main|master|sacrifice'

      - name: Delete previous sacrificial branch
        run: |
          git branch --remote -D origin/the-sacrifice

      - name: List all branches
        run: |
          git branch --all | egrep 'main|master|sacrifice'

      - name: Check out new sacrificial branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: 'the-sacrifice'

      - name: List all branches
        run: |
          git branch --all | egrep 'main|master|sacrifice'
          git diff main

      - name: Make our scripts executable
        run: chmod +x ./scripts/*.sh
      - name: Preserve upstream docs
        run: ./scripts/preserve_upstream_docs.sh

      - name: Do a diff and start a merge
        run: |
          git diff main
          git diff upstream/master
          git merge --no-ff --no-commit upstream/master
          git status
