name: Build & Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    permissions:
      pages: write
      contents: write
    strategy:
      matrix:
        node-version: ["18.x", "20.x"]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - run: corepack enable
      - run: yarn install
      - run: yarn build
      - name: Deploy to https://${{ github.actor }}.github.io/${{ github.event.repository.name }}/
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: dist
