name: OHM Upstream Sync

on:
  schedule:
    - cron: "20 5,17 * * *"
  workflow_dispatch:

jobs:
  upstream-sync:
    name: Upstream Sync
    permissions:
      contents: write
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Create sacrificial branch
        uses: peterjgrainger/action-create-branch@v3.0.0
        with:
          branch: 'the-sacrifice'
      - name: Check out our repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: 'the-sacrifice'
      - name: Check out the upstream repository
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          UPSTREAM: https://github.com/tyrasd/overpass-turbo
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@users.noreply.github.com"
          git remote add upstream "${UPSTREAM}"
          git fetch upstream master
      - name: Make our script executable
        run: chmod +x ./scripts/upstream_sync.sh
      - name: Run sync script
        run: ./scripts/upstream_sync.sh
