name: Upstream Sync

on:
  schedule:
    - cron: "20 5,17 * * *"
  workflow_dispatch:

jobs:
  upstream-sync:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./scripts
    steps:
      - name: Check out the repository to the runner
        uses: actions/checkout@v4
      - name: Make the script files executable
        run: chmod +x upstream_sync.sh
      - name: Run sync script
        uses: upstream_sync.sh
