name: OHM Upstream Sync

on:
  schedule:
    - cron: "20 5,17 * * *"
  workflow_dispatch:

jobs:
  upstream-sync:
    name: Upstream Sync
    permissions:
      contents: write
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Check out the repository to the runner
        uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - name: Make the script files executable
        run: chmod +x ./scripts/upstream_sync.sh
      - name: Run sync script
        run: ./scripts/upstream_sync.sh
